### PR TITLE
`Bugfix` Update JBCefBrowser and enable cache to work everywhere.

### LINKED ISSUE #55: Storing Credentials does not work reliably with runIDE
### Describe the bug
Currently Orion uses JCEF's settings to configure it to store credentials locally. However these settings can only be set before the first JCEF client is instantiated. If any other plugin/component happens to also use JCEF and also happens to be loaded before Orion, the settings dont get modified. Such a scenario is given if the opened project has an open markdown file since the markdown viewer also uses JCEF and open files get loaded before Orion.

#### To Reproduce
This bug only appears when running Orion with runIde and could not be observed with installed releases yet.

0. Run Orion with runIde
1. Log in to Artemis via Orion and select to store your credentials
2. Open a markdown file in an Artemis project
3. Restart IntelliJ
4. Orion will ask for credentials to log in, even though they have been stored before
5. Close the markdown file
6. Restart IntelliJ
7. Usually it works again (unless your setup has some other plugin using JCEF)

#### Solution
The only solution I can think of would be to not reflect into the library at all but instead transfer the session tokens via the connectors and store it somewhere in the global registry or the secure password registry and write them back in the local storage on startup using javascript.

### PR DESCRIPTION
**Pull request by GunniBusch**
### Motivation and Context
Sometimes Orion does not stay logged in (like on Macs)

### Description
Removed the manual Cache path allocation. That is already done by the JetBrains wrapper.
Cache is done by [JBCefAppCache](https://github.com/JetBrains/intellij-community/blob/0895fafd5c3fe96ca4f5e65624017e7a91178839/platform/platform-api/src/com/intellij/ui/jcef/JBCefAppCache.kt#L31-L37).
Resolves #55 
### Steps for Testing

1. Install the release as described in [the readme](https://github.com/ls1intum/Orion/blob/main/README.md#testing-of-pull-requests)
2. Open an exercise in Orion
3. Close IntelliJ
4. Reopen IntelliJ
5. Be fascinated that you don't have to log back in.

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

File: src/main/java/de/tum/www1/orion/ui/assessment/OrionTemplateDiffEditorProvider.kt [hunk 1]
```diff
@@ -1,3 +1,4 @@
+@file:Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
```
Comment (Kroko-fant) [inline src/main/java/de/tum/www1/orion/ui/assessment/OrionTemplateDiffEditorProvider.kt:1]: That is a quite interesting behavior. I would guess it only occurs since the newest version of JetBrains Api

**Review by Kroko-fant — APPROVED** [review]
The proposed changes look good to me. The OrionTemplateDiffEditorProvidor change might need refactoring in the future but the code works well for now.

File: src/main/java/de/tum/www1/orion/ui/assessment/OrionTemplateDiffEditorProvider.kt (hunk 1 above)
Comment (GunniBusch) [reply src/main/java/de/tum/www1/orion/ui/assessment/OrionTemplateDiffEditorProvider.kt:1]: Yes. They changed it to internal with the commit https://github.com/JetBrains/intellij-community/commit/16c9cd96c76cdeba729f3f6c3dd1ed7adab2a95c

Comment (GunniBusch) [reply src/main/java/de/tum/www1/orion/ui/assessment/OrionTemplateDiffEditorProvider.kt:1]: > The proposed changes look good to me. The OrionTemplateDiffEditorProvidor change might need refactoring in the future but the code works well for now.
Yes. Correct. That's the next step.

**Comment by GunniBusch** [comment]
> The proposed changes look good to me. The OrionTemplateDiffEditorProvidor change might need refactoring in the future but the code works well for now.

Done with https://github.com/GunniBusch/Orion/commit/f7dc39c736c623cc12bacd3f7be3174c2b6b755d in #99

**Review by Kroko-fant — APPROVED** [review]
Works fine for me. Code looks good to me.
