### PR TITLE
[Bugfix] Prevent Crashes From Unsupported Programming Languages

### LINKED ISSUE #58: Orion crashes for Kotlin Exercises
### Describe the bug

Orion crashes when attempting to assess Kotlin programming exercises.

#### To Reproduce

1.  Generate a Kotlin programming exercise
2. Participate in it
3. Asses the submission in Orion
4. Orion crashes

#### Output in IntelliJ

<details><pre>
java.lang.NullPointerException: Parameter specified as non-null is null: method de.tum.www1.orion.exercise.registry.ImportedExercise.<init>, parameter language
	at de.tum.www1.orion.exercise.registry.ImportedExercise.<init>(ImportedExercise.kt)
	at de.tum.www1.orion.exercise.registry.OrionGlobalExerciseRegistryService.createImportFileForNewProject(OrionGlobalExerciseRegistryService.java:108)
	at de.tum.www1.orion.exercise.registry.OrionGlobalExerciseRegistryService.registerExercise(OrionGlobalExerciseRegistryService.java:94)
	at de.tum.www1.orion.exercise.OrionExerciseService$assessExercise$1$1.invoke(OrionExerciseService.kt:119)
	at de.tum.www1.orion.exercise.OrionExerciseService$assessExercise$1$1.invoke(OrionExerciseService.kt:34)
	at de.tum.www1.orion.vcs.OrionGitAdapter$clone$1.onSuccess(OrionGitAdapter.kt:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:602)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:153)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$6(CoreProgressManager.java:525)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre></details>

### PR DESCRIPTION
**Pull request by MDK5**
### Motivation and Context
Fixes #58 

### Description
Updates Orions ProgrammingLanguage enumeration to the latest version so no further parsing errors should occur. Since Orion still only really supports java (and traces of python), a warning will be shown for all other languages to inform the user they will have to configure the project manually.

### Steps for Testing
1.  Install the release as described in [the readme](https://github.com/ls1intum/Orion/blob/master/README.md#testing-of-pull-requests)
2.  Download exercises in various languages as various roles (as student, instructor and tutor)
3.  Java should work properly
4.  All other languages (except Python, which sets its sdk automatically) should show a warning

### CODE REVIEW

**Review by PatZintel — APPROVED** [review]
worked for Haskell exercise on ts1

**Review by FlorianGlombik — APPROVED** [review]
Warning was displayed for Assembler and VHDL exercises when opening the first time 👍

File: src/main/java/de/tum/www1/orion/build/instructor/OrionInstructorBuildUtil.kt [hunk 1]
```diff
@@ -40,7 +43,9 @@ enum class RepositoryCheckoutPath : CustomizableCheckoutPath {
         override fun forProgrammingLanguage(language: ProgrammingLanguage): String {
             return when (language) {
                 ProgrammingLanguage.JAVA, ProgrammingLanguage.PYTHON -> ""
-                ProgrammingLanguage.C -> return "tests"
+                ProgrammingLanguage.C -> "tests"
+                // placeholder, runTestsLocally prevents any other language from reaching this line anyways
+                else -> ""
```
Comment (MaisiKoleni) [inline src/main/java/de/tum/www1/orion/build/instructor/OrionInstructorBuildUtil.kt:48]: If this is never reached, we should throw an exception here, so we know if when messed it up.

File: src/main/resources/i18n/OrionBundle_de.properties [hunk 2]
```diff
@@ -34,9 +34,11 @@ orion.error.vcs.pushfailed.unknown=Fehler! Push nach Origin ist fehlgeschlagen.
...
-orion.error.language.notsupported=Die Programmiersprache %s wird noch nicht unterstützt!
-orion.error.sdk.notavailable=Keine SDK für das aktuelle Projekt verfügbar. SDK muss in in File->Project Structure gesetzt werden bevor Änderungen eingereicht oder Tests laufen können
+orion.error.exercise.sdkFailed=Setzen der Projekt-SDK führt zu folgender Exception: %s. Setze sie vor der Ausführung manuell unter File->Project Structure->Project SDK
+orion.error.language.import.notSupported=Die Programmiersprache %s wird (noch) nicht unterstützt! Orion hat das Reporitory heruntergeladen, aber es wird wahrscheinlich manuelle Konfiguration benötigen, um das Projekt auszuführen.
+orion.error.language.buildLocally.notSupported=Die Programmiersprache %s wird (noch) nicht unterstützt! Versuche, das Projekt manuell auszuführen.
+orion.error.language.buildLocally.noSDK=Projekt SDK nicht gesetzt. Versuche, sie unter File->Project Structure zu setzen und führe den Befehl erneut aus.
+orion.error.sdk.notAvailable=Keine SDK für das aktuelle Projekt verfügbar. SDK muss in in File->Project Structure gesetzt werden bevor Änderungen eingereicht oder Tests laufen können
```
Comment (MaisiKoleni) [inline src/main/resources/i18n/OrionBundle_de.properties:41]:
```suggestion
orion.error.sdk.notAvailable=Keine SDK für das aktuelle Projekt verfügbar. SDK muss in File->Project Structure gesetzt werden bevor Änderungen eingereicht oder Tests laufen können
```

**Review by MaisiKoleni — CHANGES_REQUESTED** [review]
See comments, code looks good otherwise.

File: src/main/java/de/tum/www1/orion/build/instructor/OrionInstructorBuildUtil.kt (hunk 1 above)
Comment (MDK5) [reply src/main/java/de/tum/www1/orion/build/instructor/OrionInstructorBuildUtil.kt]: resolved :+1:
